swagger: '2.0'
info:
  version: 1.0.0
  title: TODO list
  description:
    
    Find source code of this API [here](https://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask)

basePath: "/todo/api"
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:

  /tasks:
    get:
      tags:
        - "tasks"
      summary: "Get list of tasks with URIs"
      operationId: "todo_list.todo_list_api.get_tasks"
      responses:
        200:
          description: "Successful operation"
          # schema:
          # $ref: '#/definitions/Task'

    post:
      tags:
        - "tasks"
      summary: "Add a new task to the to-do list"
      operationId: "todo_list.todo_list_api.create_task"
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/Task'
      responses:
        404:
          description: "error: not found"
        201:
          description: "Successful operation"
          schema:
            $ref: '#/definitions/Task'
            
  /task/{task_id}:
    get:
      tags:
        - "task"
      operationId: "todo_list.todo_list_api.get_task_2"
      summary: "Find task by ID"
      description: "Returns a single task"
      parameters:
      - name: task_id
        in: path
        description: id of the task to filter on
        required: true
        type: integer
      responses:
        200:
          description: returns the task filtered on
          schema:
            $ref: '#/definitions/Task'
        404:
          description: "error: not found"
          
    put:
      tags:
        - "task"
      summary: "Update an existing task"
      description: ""
      operationId: "todo_list.todo_list_api.update_task"
      parameters:
      - name: task_id
        in: path
        description: Task object that needs to be updated
        required: true
        type: integer
      - in: body
        name: body
        schema:
          $ref: '#/definitions/Task'
      responses:
        404:
          description: "error: not found"
    delete:
      tags:
        - "task"
      summary: "Deletes a task"
      description: ""
      operationId: "todo_list.todo_list_api.delete_task"
      parameters:
      - name: "task_id"
        in: "path"
        description: "Task id to delete"
        required: true
        type: "integer"
        format: "int64"
      - in: body
        name: body
        schema:
          $ref: '#/definitions/Task'
      responses:
        404:
          description: "error: not found"

        
definitions:
  Task:
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      definition:
        type: string
      done:
        type: boolean
    xml:
      name: Task
